todo/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_change_status,

    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/manage/<int:pk>/<action>", task_change_status, name="task_change_status"),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags//create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("task/create", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
]

app_name = "todo"

todo_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=155)
    time_created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField()
    tag = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["status"]

    def __str__(self):
        return f"Content: {self.content}, status: {self.status}"

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tag")
    template_name = "todo/index.html"
    ordering = ["status", "-time_created"]


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tag_list")


def task_change_status(request, pk, action):
    task = Task.objects.get(pk=pk)

    if action == "success":
        task.status = True
    if action == "undo":
        task.status = False

    task.save()

    return HttpResponseRedirect(reverse_lazy("todo:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}
            {% endblock %}

            {% block pagination %}
{#                {% include "includes/pagination.html" %}#}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/forms.html
{% load crispy_forms_filters %}

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-primary" type="submit" value="Add">
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
    <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'todo:tag_list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
    <h1 >TODO list
        <a style="float: right" class="btn btn-primary" href="{% url 'todo:task_create' %}" >Add task</a>
    </h1>

    <br>

    {% for task in task_list %}
        <p>
            <h3>{{ task.content }}
                {% if task.status %}
                    <span style="color: green">Done</span>
                    <a style="float: right" href="{% url 'todo:task_change_status' pk=task.id action='undo' %}" class="btn btn-danger float-right-button">Undo</a>
                {% else %}
                    <span style="color: red">Not done</span>
                    <a style="float: right" href="{% url 'todo:task_change_status' pk=task.id action='success' %}" class="btn btn-success float-right-button">Complete</a>
                {% endif %}
            </h3>
        </p>

        <p>Created: {{ task.time_created }}
            {% if task.deadline %}
                Deadline: {{ task.deadline }}
            {% endif %}
        </p>

        <p>Tags:
            {% for tag in task.tag.all %}
                {{ tag.name }}
            {% endfor %}
            <a href="{% url 'todo:task_update' pk=task.id %}"
               class="manage-task-tags">Update</a>
            <a href="{% url 'todo:task_delete' pk=task.id %}"
               class="manage-task-tags">Delete</a>
        </p>


    {% endfor %}

{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Tag</h1>

    <p>Do you want to fully delete: {{ tag.name }}</p>
    <form method="POST" action="">
        {% csrf_token %}

        <input type="submit" value="Yes">
    </form>

{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create new" }} tag</h1>

    {% include 'includes/forms.html' %}

{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1 >Tags
        <a class="btn btn-primary float-right" href="{% url 'todo:tag_create' %}" >Add</a>
    </h1>

    <br>
    <table class="table">
        <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
        {% for tag in tag_list %}
            <p>
              <tr>
                <h3><td>{{ tag.name }}</td></h3>
                <td><a href="{% url 'todo:tag_update' pk=tag.id %}"
                   class="manage-task-tags">Update</a></td>
                <td><a href="{% url 'todo:tag_delete' pk=tag.id %}"
                   class="manage-task-tags">Delete</a></td>
              </tr>

        {% endfor %}
    </table>

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task</h1>

    <p>Do you want to fully delete: {{ task.name }}</p>
    <form method="POST" action="">
        {% csrf_token %}

        <input type="submit" value="Yes">
    </form>

{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create new" }} task</h1>

    {% include 'includes/forms.html' %}

{% endblock %}